vscode:
  extensions:
    - betterthantomorrow.calva
tasks:
  - init: |
      sudo wget -O /usr/local/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      sudo chmod +x /usr/local/bin/lein
    command: lein test